name: Publish And Deploy Demo
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master

    # 打包构建 Release
    - name: Build
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build
    - run: tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json

    # 打包生成 github pages 静态文件
    - name: Generate-gh-pages
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run generate:gh-pages
    
    # 提交静态文件
    # - name: commit-gh-pages
    #   with:
    #     github_token: ${{ secrets.TOKEN }}
    #   run: |
    #     git config --global user.email cinyearchan@gmail.com
    #     git config --global user.name cinyearchan
    #     git add .
    #     git commit -m "update" -a
    #     git push -u origin master
    
    # - name: Push-changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.TOKEN }}

    # - name: Deploy-gh-pages
    #   uses: actions/setup-node@master
    # - run: npm run deploy
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

    # 发布 Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    # 上传构建结果到 Release
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.tgz
        asset_name: release.tgz
        asset_content_type: application/x-tgz

    # 发布到 github pages
    - name: Publish-Github-Pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCHE: gt-pages
        FOLDER: dist

    # 部署到服务器
    # - name: Deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: |
    #       cd /root/realworld-nuxtjs
    #       wget https://github.com/cinyearchan/realworld-nuxtjs/releases/latest/download/release.tgz -O release.tgz
    #       tar zxvf release.tgz
    #       npm install --production
    #       pm2 reload pm2.config.json